// User Auth
export const REGISTER_USER_REQUEST = '[USER] REGISTER REQUEST';
export const REGISTER_USER_DONE = '[USER] REGISTER DONE';

export const LOGIN_USER_REQUEST = '[USER] LOGIN REQUEST';
export const LOGIN_USER_DONE = '[USER] LOGIN DONE';

export const SET_USER_INFO_REQUEST = '[USER] SET USER INFO REQUEST';
export const SET_USER_INFO_SUCCESS = '[USER] SET USER INFO SUCCESS';
export const SET_USER_INFO_FAILURE = '[USER] SET USER INFO FAILURE';
export const LOGOUT_USER = '[USER] LOGOUT';


// Wallet
export const FETCH_DASHBOARD_REQUEST = '[USER] DASHBOARD REQUEST';
export const FETCH_DASHBOARD_SUCCESS = '[USER] DASHBOARD SUCCESS';
export const FETCH_DASHBOARD_FAILURE = '[USER] DASHBOARD FAILURE';

export const EXCHANGE_REQUEST = '[TRANSACTION] EXCHANGE REQUEST';
export const EXCHANGE_DONE = '[TRANSACTION] EXCHANGE DONE';

export const GET_TRANSACTION_HISTORY_REQUEST = '[TRANSACTION] GET HISTORY REQUEST';
export const GET_TRANSACTION_HISTORY_SUCCESS = '[TRANSACTION] GET HISTORY SUCCESS';
export const GET_TRANSACTION_HISTORY_FAILURE = '[TRANSACTION] GET HISTORY FAILURE';

export const GET_DEPOSIT_HISTORY_REQUEST = '[DEPOSIT] GET HISTORY REQUEST';
export const GET_DEPOSIT_HISTORY_SUCCESS = '[DEPOSIT] GET HISTORY SUCCESS';
export const GET_DEPOSIT_HISTORY_FAILURE = '[DEPOSIT] GET HISTORY FAILURE';

export const GET_WITHDRAWAL_HISTORY_REQUEST = '[WITHDRAWAL] GET HISTORY REQUEST';
export const GET_WITHDRAWAL_HISTORY_SUCCESS = '[WITHDRAWAL] GET HISTORY SUCCESS';
export const GET_WITHDRAWAL_HISTORY_FAILURE = '[WITHDRAWAL] GET HISTORY FAILURE';

export const DEPOSIT_COIN_REQUEST = '[DEPOSIT] GET REQUEST';
export const DEPOSIT_COIN_DONE = '[DEPOSIT] GET DONE';

export const WITHDRAWAL_COIN_REQUEST = '[WITHDRAWAL] SEND REQUEST';
export const WITHDRAWAL_COIN_DONE = '[WITHDRAWAL] SEND DONE';


// Staking
export const GET_STAKING_REQUEST = '[STAKING] GET REQUEST';
export const GET_STAKING_SUCCESS = '[STAKING] GET SUCCESS';
export const GET_STAKING_FAILURE = '[STAKING] GET FAILURE';

export const OPEN_STAKING_POSITION_REQUEST = '[STAKING] OPEN POSITION REQUEST';
export const OPEN_STAKING_POSITION_SUCCESS = '[STAKING] OPEN POSITION SUCCESS';
export const OPEN_STAKING_POSITION_FAILURE = '[STAKING] OPEN POSITION FAILURE';

export const GET_STAKING_MONEY_REQUEST = '[STAKING] GET MONEY REQUEST';
export const GET_STAKING_MONEY_DONE = '[STAKING] GET MONEY DONE';


// Trading
export const GET_CURRENCY_TRADING_REQUEST = '[TRADING] GET CURRENCY REQUEST';
export const GET_CURRENCY_TRADING_SUCCESS = '[TRADING] GET CURRENCY SUCCESS';
export const GET_CURRENCY_TRADING_FAILURE = '[TRADING] GET CURRENCY FAILURE';

export const GET_TRADING_POSITION_REQUEST = '[TRADING] GET POSITION REQUEST';
export const GET_TRADING_POSITION_SUCCESS = '[TRADING] GET POSITION SUCCESS';
export const GET_TRADING_POSITION_FAILURE = '[TRADING] GET POSITION FAILURE';

export const ADD_TRADING_POSITION_REQUEST = '[TRADING] ADD POSITION REQUEST';
export const ADD_TRADING_POSITION_DONE = '[TRADING] ADD POSITION DONE';

export const GET_TRADING_MONEY_REQUEST = '[TRADING] GET MONEY REQUEST';
export const GET_TRADING_MONEY_DONE = '[TRADING] GET MONEY DONE';


// Admin
export const GET_DEPOSIT_LIST_REQUEST = '[ADMIN] GET DEPOSIT REQUEST';
export const GET_DEPOSIT_LIST_SUCCESS = '[ADMIN] GET DEPOSIT SUCCESS';
export const GET_DEPOSIT_LIST_FAILURE = '[ADMIN] GET DEPOSIT FAILURE';

export const GET_WITHDRAWAL_LIST_REQUEST = '[ADMIN] GET WITHDRAWAL REQUEST';
export const GET_WITHDRAWAL_LIST_SUCCESS = '[ADMIN] GET WITHDRAWAL SUCCESS';
export const GET_WITHDRAWAL_LIST_FAILURE = '[ADMIN] GET WITHDRAWAL FAILURE';

export const ACCESS_LIST_REQUEST = '[ADMIN] ACCESS LIST REQUEST';
export const ACCESS_LIST_SUCCESS = '[ADMIN] ACCESS LIST SUCCESS';
export const ACCESS_LIST_FAILURE = '[ADMIN] ACCESS LIST FAILURE';